apiVersion: v1
kind: Pod
metadata:
  name: openssl-client
spec:
  restartPolicy: Never
  containers:
  - name: openssl-client
    image: finalgene/openssh
    #command: ["sh"]
    #args: ["-c", "sleep infinity"]
    command: ["sh"]
    args: ["-c", "while true; do [ -f /var/run/secrets/spire/svid.0.pem ] && openssl s_client -connect openssl-svc:3000 -CAfile /var/run/secrets/spire/bundle.0.pem -cert /var/run/secrets/spire/svid.0.pem -key /var/run/secrets/spire/svid.0.key -state && break; sleep 1; done"]
