apiVersion: v1
kind: Service
metadata:
  name: openssl-svc
spec:
  selector:
    app.kubernetes.io/name: openssl-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: openssl-server
  labels:
    app.kubernetes.io/name: openssl-server
spec:
  restartPolicy: Never
  containers:
  - name: openssl-server
    image: finalgene/openssh
    #command: ["sh"]
    #args: ["-c", "sleep infinity"]
    command: ["sh"]
    args: ["-c", "while true; do [ -f /var/run/secrets/spire/svid.0.pem ] && openssl s_server -accept 3000 -CAfile /var/run/secrets/spire/bundle.0.pem -cert /var/run/secrets/spire/svid.0.pem -key /var/run/secrets/spire/svid.0.key -state -www && break; sleep 1; done"]
